### ISSUE TITLE
Cannot transpile from es6

### ISSUE THREAD

**Issue by ohadnav** [qodesmith/typer#5]
As I was failing to uglify the code, I tried to import `typer-npm.js` code from a local js instead of from `npm_modules`. However, I got the following error now:
```
ERROR in ./src/client/manipulation/execute/interface/test.js
Module build failed: TypeError: /Users/ohad/IdeaProjects/brainjs/src/client/manipulation/execute/interface/test.js: Property body of LabeledStatement expected node to be of a type ["Statement"] but instead got null
    at Object.validate (/Users/ohad/node_modules/babel-types/lib/definitions/index.js:109:13)
    at validate (/Users/ohad/node_modules/babel-types/lib/index.js:541:9)
    at Object.builder (/Users/ohad/node_modules/babel-types/lib/index.js:494:7)
    at BlockScoping.run (/Users/ohad/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:384:16)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/ohad/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:65:24)
    at newFn (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/ohad/IdeaProjects/brainjs/node_modules/babel-traverse/lib/context.js:150:16)
```
I literally did a binary search on the code (by commenting out half, then quarter etc. :)), and found that the problem is in `processBack` method under `// TAG DETECTION` in the last `continue;` (line 519).

I am curious as to find out why the continue is useful, as there exists no code under it.

**Comment by qodesmith** [comment]
@ohadnav The `continue` is necessary there as it will stop executing any code in the loop below it but _continue_ the iteration - in contrast with the `break` which will both prevent execution of code below it _and_ stop the loop from iterating.

As far as you're initial statement, I'm not sure I understand what you mean by this:

> I tried to import `typer-npm.js` code from a local js instead of from `npm_modules`. 

For clarification, `typer-npm.js` should only be used in node in your build scripts (gulp, grunt, babel, etc.). For instance, if you're using npm to get all your front-end dependencies in conjunction with browserify to create a single package for the browser. Otherwise, you can just include the minified version - `typer.min.js`.

In any case, help me understand what's going on here so I can address any issues with the code. Thanks.

**Comment by ohadnav** [comment]
My initial statement rephrased I copy-pasted `node_modules/.../typer-npm.js` into a local js file outside of `node_modules/` and then I required it, which also didn't work, for the reasons mentioned in the post.
I am afraid including an es5 code (i.e. the minified version) is impossible as it is es5, and `module.exports` is not a recognized object.

**Comment by qodesmith** [comment]
Can you show me how you required the copy of `typer-npm.js`? Because as far as I understand, doing something like `var typer = require('typer')` is only valid within the Node environment. If you were to copy the library to use on your own, you wouldn't want the `typer-npm.js` file, you would simply copy the `typer.js` file. Note that in the `package.json` file, it points to `typer-npm.js` so that Node will see the `module.exports` which it _needs_ as opposed to the browser.

**Comment by qodesmith** [comment]
@ohadnav whoa... ok, that's some stuff I've not seen before. So you boiled it down to the `processBack` method and that `continue`? I'm really not sure what's going on then. I'm stumped here. Is that a babel build error? I'm wondering if its something to do with the myriad of babel settings. I really don't know.

**Comment by ohadnav** [comment]
You got it right. Commenting out that continue hit the spot. My uneducated
guess is that it has to do with babel in someway :-/

**Comment by qodesmith** [comment]
@ohadnav so using the [Babel repl](https://goo.gl/sL5geS) online shows that it handles a `continue` statement in a for-loop just fine. I wonder if there's some webpack setting for Babel you might have to tweak?

**Comment by qodesmith** [comment]
Also, commenting out that continue will cause issues with `typer` parsing html that you've fed it (if that's the case).

**Comment by ohadnav** [comment]
Is there a workaround for that continue?

**Comment by qodesmith** [comment]
@ohadnav I was looking into a workaround, but I'd have to jump through hoops to break out each section of the for-loop into a function. Since this is really a niche issue with Babel, I'm going to refrain from a hack in typer's code and close this issue.
